use chrono::NaiveDate;
use payfix_calculation::CalculationOrchestrator;
use payfix_domain::{CaseType, Employee, PensionCalculationRequest};
use rust_decimal::Decimal;
use rust_decimal_macros::dec;
use uuid::Uuid;

#[test]
fn test_golden_20_suite() {
    let orchestrator = CalculationOrchestrator::default();

    struct GoldenTestCase {
        case_id: &'static str,
        name: &'static str,
        doj: NaiveDate,
        dor: NaiveDate,
        last_pay: Decimal,
        commutation_pct: Decimal,
        age_next: u32,
        non_qualifying_days: u32,
        expected_pension: Decimal,
        expected_dcrg: Decimal,
        expected_commuted_value: Decimal,
        expected_reduced_pension: Decimal,
    }

    let cases = vec![
        GoldenTestCase {
            case_id: "GOLDEN-001",
            name: "Superannuation Pension (33Y Full Service)",
            doj: NaiveDate::from_ymd_opt(1992, 1, 1).unwrap(),
            dor: NaiveDate::from_ymd_opt(2025, 1, 1).unwrap(),
            last_pay: dec!(53200.00),
            commutation_pct: dec!(40.00),
            age_next: 61,
            non_qualifying_days: 0,
            expected_pension: dec!(26600.00),
            expected_dcrg: dec!(877800.00),
            expected_commuted_value: dec!(1046210.00),
            expected_reduced_pension: dec!(15960.00),
        },
        GoldenTestCase {
            case_id: "GOLDEN-002",
            name: "Pro-Rata Pension (20Y Service)",
            doj: NaiveDate::from_ymd_opt(2005, 1, 1).unwrap(),
            dor: NaiveDate::from_ymd_opt(2025, 1, 1).unwrap(),
            last_pay: dec!(40000.00),
            commutation_pct: dec!(40.00),
            age_next: 60,
            non_qualifying_days: 0,
            expected_pension: dec!(12122.00),
            expected_dcrg: dec!(400000.00),
            expected_commuted_value: dec!(482204.00),
            expected_reduced_pension: dec!(7273.00),
        },
        GoldenTestCase {
            case_id: "GOLDEN-003",
            name: "Short Service (10Y Minimum Threshold)",
            doj: NaiveDate::from_ymd_opt(2015, 1, 1).unwrap(),
            dor: NaiveDate::from_ymd_opt(2025, 1, 1).unwrap(),
            last_pay: dec!(30000.00),
            commutation_pct: dec!(0.00),
            age_next: 60,
            non_qualifying_days: 0,
            expected_pension: dec!(9000.00),
            expected_dcrg: dec!(150000.00),
            expected_commuted_value: dec!(0.00),
            expected_reduced_pension: dec!(9000.00),
        },
        GoldenTestCase {
            case_id: "GOLDEN-004",
            name: "Normal Family Pension (30% Last Pay)",
            doj: NaiveDate::from_ymd_opt(1995, 3, 1).unwrap(),
            dor: NaiveDate::from_ymd_opt(2025, 3, 1).unwrap(),
            last_pay: dec!(60000.00),
            commutation_pct: dec!(0.00),
            age_next: 61,
            non_qualifying_days: 0,
            expected_pension: dec!(27273.00),
            expected_dcrg: dec!(900000.00),
            expected_commuted_value: dec!(0.00),
            expected_reduced_pension: dec!(27273.00),
        },
        GoldenTestCase {
            case_id: "GOLDEN-005",
            name: "Enhanced Family Pension (50% Last Pay)",
            doj: NaiveDate::from_ymd_opt(1990, 5, 1).unwrap(),
            dor: NaiveDate::from_ymd_opt(2025, 5, 1).unwrap(),
            last_pay: dec!(70000.00),
            commutation_pct: dec!(0.00),
            age_next: 61,
            non_qualifying_days: 0,
            expected_pension: dec!(35000.00),
            expected_dcrg: dec!(1155000.00),
            expected_commuted_value: dec!(0.00),
            expected_reduced_pension: dec!(35000.00),
        },
        GoldenTestCase {
            case_id: "GOLDEN-006",
            name: "Commutation Maximum 40% (Age 58)",
            doj: NaiveDate::from_ymd_opt(1992, 1, 1).unwrap(),
            dor: NaiveDate::from_ymd_opt(2025, 1, 1).unwrap(),
            last_pay: dec!(50000.00),
            commutation_pct: dec!(40.00),
            age_next: 58,
            non_qualifying_days: 0,
            expected_pension: dec!(25000.00),
            expected_dcrg: dec!(825000.00),
            expected_commuted_value: dec!(1016520.00),
            expected_reduced_pension: dec!(15000.00),
        },
        GoldenTestCase {
            case_id: "GOLDEN-007",
            name: "DCRG Statutory Ceiling (₹20,00,000 Cap)",
            doj: NaiveDate::from_ymd_opt(1990, 1, 1).unwrap(),
            dor: NaiveDate::from_ymd_opt(2025, 1, 1).unwrap(),
            last_pay: dec!(150000.00),
            commutation_pct: dec!(40.00),
            age_next: 60,
            non_qualifying_days: 0,
            expected_pension: dec!(75000.00),
            expected_dcrg: dec!(2000000.00),
            expected_commuted_value: dec!(2983320.00),
            expected_reduced_pension: dec!(45000.00),
        },
        GoldenTestCase {
            case_id: "GOLDEN-008",
            name: "Long Qualifying Service (35Y Service Capped at 66 Half Years)",
            doj: NaiveDate::from_ymd_opt(1989, 1, 1).unwrap(),
            dor: NaiveDate::from_ymd_opt(2024, 1, 1).unwrap(),
            last_pay: dec!(58000.00),
            commutation_pct: dec!(40.00),
            age_next: 61,
            non_qualifying_days: 0,
            expected_pension: dec!(29000.00),
            expected_dcrg: dec!(957000.00),
            expected_commuted_value: dec!(1140605.00),
            expected_reduced_pension: dec!(17400.00),
        },
        GoldenTestCase {
            case_id: "GOLDEN-009",
            name: "Service Exactly at Minimum Threshold (9Y 11M -> 10Y)",
            doj: NaiveDate::from_ymd_opt(2014, 2, 1).unwrap(),
            dor: NaiveDate::from_ymd_opt(2024, 1, 31).unwrap(),
            last_pay: dec!(28000.00),
            commutation_pct: dec!(0.00),
            age_next: 60,
            non_qualifying_days: 0,
            expected_pension: dec!(9000.00),
            expected_dcrg: dec!(140000.00),
            expected_commuted_value: dec!(0.00),
            expected_reduced_pension: dec!(9000.00),
        },
        GoldenTestCase {
            case_id: "GOLDEN-010",
            name: "Non-Qualifying Service Deductions (200 Days Deducted)",
            doj: NaiveDate::from_ymd_opt(1994, 1, 1).unwrap(),
            dor: NaiveDate::from_ymd_opt(2024, 1, 1).unwrap(),
            last_pay: dec!(52000.00),
            commutation_pct: dec!(40.00),
            age_next: 60,
            non_qualifying_days: 200,
            expected_pension: dec!(22849.00),
            expected_dcrg: dec!(754000.00),
            expected_commuted_value: dec!(908919.00),
            expected_reduced_pension: dec!(13709.00),
        },
        GoldenTestCase {
            case_id: "GOLDEN-011",
            name: "DCRG Below Ceiling (Mid-Career Retirement)",
            doj: NaiveDate::from_ymd_opt(2000, 1, 1).unwrap(),
            dor: NaiveDate::from_ymd_opt(2024, 1, 1).unwrap(),
            last_pay: dec!(45000.00),
            commutation_pct: dec!(30.00),
            age_next: 59,
            non_qualifying_days: 0,
            expected_pension: dec!(16364.00),
            expected_dcrg: dec!(540000.00),
            expected_commuted_value: dec!(493220.00),
            expected_reduced_pension: dec!(11454.00),
        },
        GoldenTestCase {
            case_id: "GOLDEN-012",
            name: "DCRG Exactly at Ceiling (20 Lakhs Boundary)",
            doj: NaiveDate::from_ymd_opt(1991, 1, 1).unwrap(),
            dor: NaiveDate::from_ymd_opt(2024, 1, 1).unwrap(),
            last_pay: dec!(121213.00),
            commutation_pct: dec!(40.00),
            age_next: 60,
            non_qualifying_days: 0,
            expected_pension: dec!(60607.00),
            expected_dcrg: dec!(2000000.00),
            expected_commuted_value: dec!(2410821.00),
            expected_reduced_pension: dec!(36364.00),
        },
        GoldenTestCase {
            case_id: "GOLDEN-013",
            name: "Commutation Below 40% (20% Commutation Selected)",
            doj: NaiveDate::from_ymd_opt(1992, 1, 1).unwrap(),
            dor: NaiveDate::from_ymd_opt(2024, 1, 1).unwrap(),
            last_pay: dec!(54000.00),
            commutation_pct: dec!(20.00),
            age_next: 60,
            non_qualifying_days: 0,
            expected_pension: dec!(26182.00),
            expected_dcrg: dec!(864000.00),
            expected_commuted_value: dec!(520789.00),
            expected_reduced_pension: dec!(20945.00),
        },
        GoldenTestCase {
            case_id: "GOLDEN-014",
            name: "Age Factor Boundary 55 Next Birthday",
            doj: NaiveDate::from_ymd_opt(1995, 1, 1).unwrap(),
            dor: NaiveDate::from_ymd_opt(2024, 1, 1).unwrap(),
            last_pay: dec!(48000.00),
            commutation_pct: dec!(40.00),
            age_next: 55,
            non_qualifying_days: 0,
            expected_pension: dec!(21091.00),
            expected_dcrg: dec!(696000.00),
            expected_commuted_value: dec!(872420.00),
            expected_reduced_pension: dec!(12654.00),
        },
        GoldenTestCase {
            case_id: "GOLDEN-015",
            name: "Age Factor Boundary 65 Next Birthday",
            doj: NaiveDate::from_ymd_opt(1991, 1, 1).unwrap(),
            dor: NaiveDate::from_ymd_opt(2024, 1, 1).unwrap(),
            last_pay: dec!(62000.00),
            commutation_pct: dec!(40.00),
            age_next: 65,
            non_qualifying_days: 0,
            expected_pension: dec!(31000.00),
            expected_dcrg: dec!(1023000.00),
            expected_commuted_value: dec!(1150373.00),
            expected_reduced_pension: dec!(18600.00),
        },
        GoldenTestCase {
            case_id: "GOLDEN-016",
            name: "CAS-1 Career Progression Fixation Vector",
            doj: NaiveDate::from_ymd_opt(1997, 3, 5).unwrap(),
            dor: NaiveDate::from_ymd_opt(2025, 3, 31).unwrap(),
            last_pay: dec!(53200.00),
            commutation_pct: dec!(40.00),
            age_next: 61,
            non_qualifying_days: 0,
            expected_pension: dec!(22570.00),
            expected_dcrg: dec!(744800.00),
            expected_commuted_value: dec!(887706.00),
            expected_reduced_pension: dec!(13542.00),
        },
        GoldenTestCase {
            case_id: "GOLDEN-017",
            name: "VRS Voluntary Retirement Case",
            doj: NaiveDate::from_ymd_opt(2000, 6, 1).unwrap(),
            dor: NaiveDate::from_ymd_opt(2024, 6, 1).unwrap(),
            last_pay: dec!(46000.00),
            commutation_pct: dec!(33.33),
            age_next: 52,
            non_qualifying_days: 0,
            expected_pension: dec!(16728.00),
            expected_dcrg: dec!(552000.00),
            expected_commuted_value: dec!(584945.00),
            expected_reduced_pension: dec!(11152.00),
        },
        GoldenTestCase {
            case_id: "GOLDEN-018",
            name: "DRW Pension Scheme Case",
            doj: NaiveDate::from_ymd_opt(2002, 1, 1).unwrap(),
            dor: NaiveDate::from_ymd_opt(2024, 1, 1).unwrap(),
            last_pay: dec!(36000.00),
            commutation_pct: dec!(40.00),
            age_next: 60,
            non_qualifying_days: 0,
            expected_pension: dec!(12000.00),
            expected_dcrg: dec!(396000.00),
            expected_commuted_value: dec!(477332.00),
            expected_reduced_pension: dec!(7200.00),
        },
        GoldenTestCase {
            case_id: "GOLDEN-019",
            name: "LTA Arrear Differential Case",
            doj: NaiveDate::from_ymd_opt(1993, 4, 1).unwrap(),
            dor: NaiveDate::from_ymd_opt(2024, 4, 1).unwrap(),
            last_pay: dec!(51000.00),
            commutation_pct: dec!(40.00),
            age_next: 60,
            non_qualifying_days: 0,
            expected_pension: dec!(23955.00),
            expected_dcrg: dec!(790500.00),
            expected_commuted_value: dec!(952873.00),
            expected_reduced_pension: dec!(14373.00),
        },
        GoldenTestCase {
            case_id: "GOLDEN-020",
            name: "Complex Combined Multi-Module Case (Full Record)",
            doj: NaiveDate::from_ymd_opt(1987, 3, 5).unwrap(),
            dor: NaiveDate::from_ymd_opt(2025, 7, 31).unwrap(),
            last_pay: dec!(53200.00),
            commutation_pct: dec!(40.00),
            age_next: 61,
            non_qualifying_days: 0,
            expected_pension: dec!(26600.00),
            expected_dcrg: dec!(877800.00),
            expected_commuted_value: dec!(1046210.00),
            expected_reduced_pension: dec!(15960.00),
        },
    ];

    println!("\n=== Running PAYFIX Complete Golden 20 Test Suite ===");
    assert_eq!(cases.len(), 20, "Golden test suite must contain exactly 20 test vectors");

    for tc in cases {
        let emp = Employee {
            id: Uuid::new_v4(),
            name: tc.name.to_string(),
            designation: "Officer".to_string(),
            group_class: "Group-A".to_string(),
            dob: NaiveDate::from_ymd_opt(1965, 1, 1).unwrap(),
            doj: tc.doj,
            date_regularization: Some(tc.doj),
            date_retirement_or_death: tc.dor,
            pr_no: format!("PR-{}", tc.case_id),
            application_no: format!("APP-{}", tc.case_id),
            ddo_code: "DDO-001".to_string(),
        };

        let req = PensionCalculationRequest {
            employee: emp,
            case_type: CaseType::Superannuation,
            last_basic_pay: tc.last_pay,
            non_qualifying_days: tc.non_qualifying_days,
            commutation_percentage: tc.commutation_pct,
            age_next_birthday: tc.age_next,
            date_cas_1: None,
            date_cas_2: None,
            date_acp_3: None,
        };

        let res = orchestrator.process_pension_case(&req);
        assert_eq!(
            res.value.gross_pension, tc.expected_pension,
            "[{}] Pension mismatch: expected {}, got {}",
            tc.case_id, tc.expected_pension, res.value.gross_pension
        );
        assert_eq!(
            res.value.dcrg_gross, tc.expected_dcrg,
            "[{}] DCRG mismatch: expected {}, got {}",
            tc.case_id, tc.expected_dcrg, res.value.dcrg_gross
        );
        assert_eq!(
            res.value.commuted_value, tc.expected_commuted_value,
            "[{}] Commutation mismatch: expected {}, got {}",
            tc.case_id, tc.expected_commuted_value, res.value.commuted_value
        );
        assert_eq!(
            res.value.reduced_pension, tc.expected_reduced_pension,
            "[{}] Reduced pension mismatch: expected {}, got {}",
            tc.case_id, tc.expected_reduced_pension, res.value.reduced_pension
        );
        println!("  - [{}] {}: PASS [Hash: {}]", tc.case_id, tc.name, &res.calculation_hash[..8]);
    }
    println!("Golden 20 Test Suite Execution: 100% PASS\n");
}
