import React from 'react';
import type { GeneratedDocument } from '../../types/api';
import { X, Printer, ShieldCheck, Lock } from 'lucide-react';

interface DocumentPreviewModalProps {
  document: GeneratedDocument | null;
  onClose: () => void;
}

export const DocumentPreviewModal: React.FC<DocumentPreviewModalProps> = ({ document: doc, onClose }) => {
  if (!doc) return null;

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 backdrop-blur-sm p-4 text-xs">
      <div className="bg-slate-900 border border-slate-800 rounded-xl max-w-3xl w-full max-h-[90vh] flex flex-col shadow-2xl overflow-hidden">
        {/* Modal Header */}
        <div className="flex items-center justify-between p-4 border-b border-slate-800 bg-slate-950">
          <div className="flex items-center space-x-2">
            <ShieldCheck className="w-5 h-5 text-blue-400" />
            <div>
              <h3 className="font-bold text-slate-100 text-sm">{doc.title}</h3>
              <p className="text-[11px] text-slate-400 font-mono">Template: {doc.template_code} v{doc.template_version}</p>
            </div>
          </div>

          <div className="flex items-center space-x-2">
            <button
              onClick={handlePrint}
              className="flex items-center space-x-1 px-3 py-1.5 bg-slate-800 hover:bg-slate-700 text-slate-200 font-bold rounded-lg transition"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>Print</span>
            </button>
            <button
              onClick={onClose}
              className="p-1.5 text-slate-400 hover:text-slate-200 transition"
            >
              <X className="w-4 h-4" />
            </button>
          </div>
        </div>

        {/* Modal Body - Official Document Rendering Canvas */}
        <div className="flex-1 overflow-y-auto p-6 bg-slate-950 flex justify-center">
          <div className="bg-slate-900 border border-slate-800 p-8 rounded-xl max-w-2xl w-full shadow-xl text-slate-200 font-serif space-y-6">
            <div className="text-center border-b border-slate-800 pb-4 space-y-1">
              <p className="font-bold text-slate-400 text-xs tracking-widest uppercase font-sans">Government of Tripura</p>
              <h2 className="text-lg font-black text-slate-100 uppercase tracking-wide font-sans">{doc.title}</h2>
              <p className="text-[11px] text-blue-400 font-mono font-bold font-sans">Official Sanction Order Document</p>
            </div>

            {/* Document Content Render */}
            <div
              className="prose prose-invert max-w-none text-xs leading-relaxed space-y-4"
              dangerouslySetInnerHTML={{ __html: doc.content_html }}
            />

            {/* Document Footer & Digital Signature Badge */}
            <div className="border-t border-slate-800 pt-4 flex items-center justify-between text-[10px] text-slate-400 font-sans">
              <div>
                <p><span className="font-bold text-slate-300">Generated By:</span> {doc.generated_by}</p>
                <p><span className="font-bold text-slate-300">Timestamp:</span> {new Date(doc.generated_at).toLocaleString()}</p>
              </div>

              <div className="bg-slate-950 border border-slate-800 p-2.5 rounded-lg text-right font-mono space-y-0.5">
                <p className="text-emerald-400 font-bold flex items-center justify-end space-x-1">
                  <Lock className="w-3 h-3" />
                  <span>SHA-256 SEALED DIGEST</span>
                </p>
                <p className="text-[9px] text-slate-500">{doc.sha256_hash.substring(0, 32)}...</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
