FROM rust:latest as builder
WORKDIR /app
COPY . .
RUN cargo build --release --bin payfix-api

FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y ca-certificates libssl-dev curl && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY --from=builder /app/target/release/payfix-api /app/payfix-api
EXPOSE 8085
ENV PORT=8085
ENV RUST_LOG=info,payfix_api=debug
CMD ["/app/payfix-api"]
